[package]
name = "snippet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
crossterm = "0.28.1"
ratatui = "0.28.1"
rayon = "1.10.0"
serde = { version = "1.0.202", features = ["serde_derive"] }
serde_json = "1.0.120"
